name = "AllysPack"
author = "ally"
version = "0.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "418feb111ee956e75938514c2b9db9990cbc1cc682f912f48d65e35cdf45d824"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
