name = "AllysPack"
author = "ally"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e93562b6e0b27499c479af4417424ff15247888381bbbc446df3be07a1d7759c"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
