name = "AllysPack"
author = "ally"
version = "0.0.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a2fd139c82cd4a77d90e83382c5ea84d8faf9c3b330682999b871a0e946b2bf5"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
