name = "AllysPack"
author = "ally"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03eebfcb5d4fc91ae640431227cde377f77478febcc567aee93749edb5488b00"

[versions]
fabric = "0.14.10"
minecraft = "1.19.2"
